### ISSUE TITLE
Spelling Mistake in Readme.md 

### ISSUE THREAD

**Issue by DataCrusade1999** [DSC-COEA-Ambajogai/Hacktoberfest2020#316]
In the Readme.md of the repository, there are several places where "Hacktoberfest" is misspelled as "Hactoberfest".

**Comment by DataCrusade1999** [comment]
I know I should have pointed out this issue in the earlier issue but I forgot.
Sorry.

**Comment by VenkatVuddagiri** [comment]
Hey can I work on this issue?

**Comment by DataCrusade1999** [comment]
> Hey can I work on this issue?

@VenkatVuddagiri  Sure

**Comment by DataCrusade1999** [comment]
@VenkatVuddagiri  but ask the maintainer first.

**Comment by VenkatVuddagiri** [comment]
That's what I did XD @DataCrusade1999

**Comment by komalswami** [comment]
yeah  i merged your pr
